### ISSUE TITLE
IntelliSense popup for opcodes

### ISSUE THREAD

**Issue by SmallRoomLabs** [chunkypixel/atari-dev-studio#10]
You know what would be awesome? Being able to hover over the INC you just typed in and have an IntelliSense-popup display this:

<img width="412" alt="Screen Shot 2019-05-05 at 11 51 09 AM" src="https://user-images.githubusercontent.com/325326/57192032-52ce3280-6f2c-11e9-94e5-e88ddfb0dea2.png">

Maybe something to code some nasty rainy and cold day when you have nothing better to do ;-)

**Comment by SmallRoomLabs** [comment]
I've become a bit intrigued about the VC extensions in general. I almost feel like digging into this myself and learn something new in the process....

**Comment by chunkypixel** [comment]
Sounds interesting.  I haven't done much at all on that side of things apart from provide a language template.  Will certainly put this sort of thing on the list of things to investigate around intellisense.  Do you have a site that lists all of this type of information I could check out? 

Certainly been fun to learn!

**Comment by SmallRoomLabs** [comment]
If you mean a site with info about IntelliSense I've got nothing - for me that would be a process to learn from scratch - as would writing VC extensions. 

For the opcodes info I usually use [masswerk.at/6502](https://www.masswerk.at/6502/6502_instruction_set.html#LSR)

**Comment by chunkypixel** [comment]
Mats added pull request #12 with new hover features for for 6502 and VCS tooltips.  Updated process to allow each language to have it;s own hover tooltips based on this process.
