### ISSUE TITLE
Binary values incorrect in the horizontal motion documentation

### ISSUE THREAD

**Issue by andyjp** [chunkypixel/atari-dev-studio#14]
![image](https://user-images.githubusercontent.com/8158746/72282815-7a24e580-360b-11ea-81cf-16448c8717f5.png)

Looks like it should be:

    - bit7..4=0111 ($70): Left 7 clock
    - bit7..4=1000 ($80): Right 8 clock
    - bit7..4=1001 ($90): Right 7 clock
    - bit7..4=1010 ($A0): Right 6 clock
    - bit7..4=1011 ($B0): Right 5 clock
    - bit7..4=1100 ($C0): Right 4 clock
    - bit7..4=1101 ($D0): Right 3 clock
    - bit7..4=1110 ($E0): Right 2 clock
    - bit7..4=1111 ($F0): Right 1 clock

**Comment by chunkypixel** [comment]
Thanks @andyjp! I'll fix that for the next release.

**Comment by chunkypixel** [comment]
Fixed tables for:
* Horizontal Motion Player 0
* Horizontal Motion Player 1
* Horizontal Motion Missile 0
* Horizontal Motion Missile 1
* Horizontal Motion Ball
