### ISSUE TITLE
Colouring higher bank numbers & regions

### ISSUE THREAD

**Issue by MikeBrownEmplas** [chunkypixel/atari-dev-studio#15]
Hello, please could we have the same colouring for referencing higher bank numbers, such as 11, 23 etc like we do for 1, 2, 3?

It loses that nice colour highlighting on bigger ROMs with more banks.

Also, collapsible regions would be a game-changer, I'm working on a 64KB game at the moment and that would be amazing!

Keep up the good work!

**Comment by chunkypixel** [comment]
Hi Mike, 
thanks for your requests.  

I have added region folding for both batari Basic and 7800basic.

Usage:
;#region " XXX "
;#endregion

Region can have an optional name (ie. " XXX ") as shown above.

**Comment by chunkypixel** [comment]
Updated bank references for both batari Basic and 7800basic to the following:
* bank1-bank8 => bank1-bank24

**Comment by MikeBrownEmplas** [comment]
Fantastic! Thank you!

Looking forward to updating this evening and organising my very large ROM!
