### ISSUE TITLE
Colour Palette for 2600

### ISSUE THREAD

**Issue by MikeBrownEmplas** [chunkypixel/atari-dev-studio#16]
Hello, could we have the NTSC and PAL Colour Pallet Guide for the 2600 please?

**Comment by chunkypixel** [comment]
@MikeBrownEmplas I do need to expand this area for the 2600! I hope you get to it soon!

**Comment by chunkypixel** [comment]
I have started working on the selector to allow palettes to be selected for the 2600.

**Comment by chunkypixel** [comment]
Updated the 7800 palettes and worked out how I can put in 2600 along with those. Hopefully add the next few days.

**Comment by chunkypixel** [comment]
Done - coming in v0.4.6

**Comment by MikeBrownEmplas** [comment]
Just loaded this up, it's perfect thank you. Mike @G2 Games

**Comment by chunkypixel** [comment]
Pleasure! Again sorry it took so long!
