### ISSUE TITLE
Sprite Editor

### ISSUE THREAD

**Issue by MikeBrownEmplas** [chunkypixel/atari-dev-studio#17]
Could we have a 2600 Sprite Editor please? Thank you.

**Comment by chunkypixel** [comment]
@MikeBrownEmplas I do need to expand this area for the 2600! I hope you get to it soon - will require some sizing configurations, color limitations (single or DPC+) and export to binary.

**Comment by chunkypixel** [comment]
I have started working on the selector to allow palettes and sizing configurations to be selected for the 2600.

**Comment by chunkypixel** [comment]
Partly implemented in v0.4.6. You can now choose 7800 or 2600 and NTSC or PAL palettes.

More work required for DPC+ sprites though and exporting...

**Comment by chunkypixel** [comment]
Done in v0.4.6. 
- You can now choose 7800 or 2600 and NTSC or PAL palettes.
- Exporting to batari Basic or assembly source has been completed.
