### ISSUE TITLE
New to this so bear with me

### ISSUE THREAD

**Issue by sexyUnderwriter** [chunkypixel/atari-dev-studio#18]
I just stumbled across your project and I think I am in heaven! I got really excited about the Vb version of BatariBasic, but it was really wonky on my machine and wouldn't natively work in mac.

So one debug issue I found - in Mac Ox 10.13.6 (High Sierra), Stella is an untrusted program.  What this means is that in order for it to launch natively in Visual Studio Code, the user has to have the system trust it.  This is easily accomplished in settings, but the error message displayed doesn't give you any clue as to why Stella isn't launching.  More importantly, if a user hasn't manually turned on viewing all hidden files, the path is impossible to find in Finder.

Unfortunately, I didn't get a copy of the error before it cleared, and now my system "trusts" stella as I told it to overrule suppressing it's launch.

**Comment by chunkypixel** [comment]
@sexyUnderwriter 
Thanks for notifying me - I'm not a mac user generally so can I try and gather a little more info about it?  Not sure I can do anything via VS Code here but I could write up some basic instructions or advise that people my encounter the problem.

Can I assume it may be generally outlined here?
https://support.apple.com/en-us/HT202491

and the user can 'trust' Stella here?
System Preferences->Security & Privacy->General

Thanks again and hope you enjoy the extension - hoping to add a few more features to the sprite editor for 2600 users shortly.

**Comment by sexyUnderwriter** [comment]
Yes - that’s correct, except in my case the Visual Studio never even gave me the error that the app was unsigned. I finally realized this when I checked in settings and it informed me that Mac OS had prevented it from loading. Once I told it to temporarily override the suppression, it loaded just fine. 

Hope this helps!
