### ISSUE TITLE
Annoying popup message at start

### ISSUE THREAD

**Issue by SmallRoomLabs** [chunkypixel/atari-dev-studio#2]
Even if it autocloses after like 10 seconds the "Welcome to Atari Dev Studio (v0.1.0)!" popup is a bit annoying...

**Comment by chunkypixel** [comment]
No probs. Now that I have the status bar auto initialising I can remove it.  Previously things only happened when you did something ie. compile or open the welcome so wanted something to show it was ready.

**Comment by chunkypixel** [comment]
Completed in release v0.1.1
