### ISSUE TITLE
Replace bB version with the 64-bit only (macOS)

### ISSUE THREAD

**Issue by chunkypixel** [chunkypixel/atari-dev-studio#20]
It appears there maybe some sort of issue in potentially determining the 32/64-bit version in macOS for some users. Replace with the 64-bit version only to see if that removes the issue.  This will fall inline with Stella only being 64-bit also.

**Discussion**
https://atariage.com/forums/topic/290365-atari-dev-studio-for-homebrew-development-release/?do=findComment&comment=4473674

**Comment by Generation2Games** [comment]
Will this fix the ERROR: couldn't find bB binaries for Darwin(x86_64). Exiting. problem I am getting as I have just bought a new Mac today?

**Comment by chunkypixel** [comment]
Refer #22 
Going to leave this for now and issue has been identified and fixed.
