### ISSUE TITLE
Stella quit unexpectedly (macOS 10.13.6)

### ISSUE THREAD

**Issue by sexyUnderwriter** [chunkypixel/atari-dev-studio#25]
I've updated to the most recent release for MacOS and am still getting a Stella error when I close the app via the window. Perhaps this is a Stella bug?

**Comment by chunkypixel** [comment]
Hi! I'm not sure what might be causing that - I'll have a play and see if it's something I can fix...

**Comment by Generation2Games** [comment]
I can confirm I sometimes get this too.

**Comment by Generation2Games** [comment]
Also, I wondered if you could help, it's probably me as getting used to Mac, but I have a dual monitor setup. Every time I launch the Stella app from ADS, it launches on the code screen, and doesn't remember I moved it to the other screen. Is this VSC or ADS related?

**Comment by Generation2Games** [comment]
VSC = Visual Studio Code ADS = Atari Dev Studio

**Comment by chunkypixel** [comment]
Hey guys - does the newest release 1.4.4 work a little better? Has the latest Stella 6.1.

**Comment by chunkypixel** [comment]
> VSC = Visual Studio Code ADS = Atari Dev Studio

It may not have permissions to save changes to any config file that is produced - I'll need to check on my virtual environment.

**Comment by Generation2Games** [comment]
Since the update I have not had a single crash. I'll report back if this happens. Thank you once again!

**Comment by sexyUnderwriter** [comment]
With all the craziness of the covid-19 issue I’ve not had a chance to try it again. I’ll try to do it this weekend.
