### ISSUE TITLE
Apple Touch Bar Support

### ISSUE THREAD

**Issue by Generation2Games** [chunkypixel/atari-dev-studio#26]
Hi, I was wondering if there is a way to add the action bar at the bottom (Home / Sprite / Compile / Launch) into the Apple Touch Bar? That WOULD be slick!

Also good to see regular updates on here! Keep up the good work!

**Comment by chunkypixel** [comment]
Hi @Generation2Games! Hope you are surviving this world crisis ok!

I have found an extension for VS Code which does offer such a feature here: https://marketplace.visualstudio.com/items?itemName=felipe.nasc-touchbar&ssr=false#overview

I'll check out the source and see if I can implement it into Atari Dev Studio for you!

**Comment by Generation2Games** [comment]
The apocalypse is underwhelming but using the time to learn and finish this game. Hope all is well with you?

Would be fantastic if this was a ADS feature, would boost productivity for sure!

**Comment by chunkypixel** [comment]
I'm well - hope you are too.  I have started adding this but I read I could test it (the touchbar) with some sort of program in macOS.  Hopefully soon!!

**Comment by chunkypixel** [comment]
Added support in release v0.4.5

Ok - just an initial test to make sure it works.  I haven't set any icons as yet but they display and activate on a touchbar emulator on my VM.  If you can confirm they work Ok we can look to expand the features.

**Comment by MikeBrownEmplas** [comment]
That is excellent, I can see "build" and "build and run" in the Touch Bar. Would be great to put buttons for the other specific tools you provide in the suite, in time, no rush. Great progress!

**Comment by chunkypixel** [comment]
@MikeBrownEmplas 
Great thanks for checking them out! I'll add the additional ones and with icons probably in the next release.
