### ISSUE TITLE
Stella not loading in Linux distro

### ISSUE THREAD

**Issue by sexyUnderwriter** [chunkypixel/atari-dev-studio#28]
So I recently moved over to Linux Mint to revive an older laptop and got Visual Studio Code running through the flatpak install.  Got the Atari Dev Studion going and all seemed fine until I tried to compile and test a game - got an error indicating there was no Stella emulator present.  I separately tried to install Stella and point to my own install of it, to no avail.  
When digging into the path it appears that perhaps there is a bug in the path? I didn't see a path folder called "ia32".  I assume this is supposed to be "x32"?  I tried to change the folder to ia32 and it still didn't work.   I'm not fantastic with Linux, but I put in my own very basic path (like to the Desktop) for my own copy of Stella and it still didn't like it.  
Any thoughts?

Here's what I get when I try to use the built in reference.
Complete.
Build complete.
Verifying compiled file(s)...
Cleaning up files generated during compilation...
Moving compiled file(s) to 'bin' folder...
Moving debugger file(s) to 'bin' folder...

Launching Stella emulator...
/bin/sh: /home/chris/.var/app/com.visualstudio.code/data/vscode/extensions/chunkypixel.atari-dev-studio-0.3.0/out/bin/emulators/stella/linux/ia32/stella: No such file or directory

**Comment by chunkypixel** [comment]
Hi,
I'll need to check that out - strange that the path would have changed in some way. Will investigate.

**Comment by chunkypixel** [comment]
My VM has borked itself today.  Will need to reinstall (using Ubuntu). I've updated Stella to 6.1.1 in the latest release v0.4.5 if you can take a look.

**Comment by chunkypixel** [comment]
I've installed Ubuntu 19.10 and confirmed the latest release of Atari Dev Studio with Stella 6.1.1 opens and runs successfully.
Please let me know if there is still and issue for you.

**Comment by sexyUnderwriter** [comment]
I installed a 64 bit version of Ubuntu and it appears to be working fine.  I think it has to do with the 32 bit Flatpak distro of Visual Studio Code, as it isn't officially supported by MSFT.

**Comment by chunkypixel** [comment]
Thanks for reporting back - glad it's working for you now.
