### ISSUE TITLE
Add ability to select both NTSC and PAL palettes

### ISSUE THREAD

**Issue by chunkypixel** [chunkypixel/atari-dev-studio#29]
Users need to be able to choose between NTSC and PAL palettes.  Implement the following:

- Add PAL palette to configuration 
- Update selector on Create Project dialog to list PAL
- Add new selector to Palette window to allow change on the fly between NTSC and PAL

Need to also incorporate 2600 palettes into this process.

**Comment by chunkypixel** [comment]
Added selectors to Create Project dialog and Palette window
Added temp PAL palette

**Comment by chunkypixel** [comment]
Updated NTSC palette and added PAL palette (7800) based on A7800 (warm).  2600 palettes can now be catered for - just need to be entered.

**Comment by chunkypixel** [comment]
Done in v0.4.6
2600 palettes (NTSC and PAL) have been added.

**Comment by MikeBrownEmplas** [comment]
Truly amazing!!
