### ISSUE TITLE
Wrong breadcrumb path in help message

### ISSUE THREAD

**Issue by SmallRoomLabs** [chunkypixel/atari-dev-studio#3]
When trying to compile & run on OSX for the first time the help message is not so helpful since it points you to the list of extensions rather than the settings of them. (Also the 's' in Preferences is missing as well)

> WARNING: You must provide a path to your Stella emulator before you can launch your game. Review your selection in Preference -> Extensions -> Atari Dev Studio.

should be

> WARNING: You must provide a path to your Stella emulator before you can launch your game. Review your selection in Preference**s** -> **Settings** -> Extensions -> Atari Dev Studio.

**Comment by chunkypixel** [comment]
Brilliant thank you! I poured over the readme for hours and you just don't always see the little details. Really appreciate you raising it 👍

**Comment by chunkypixel** [comment]
Completed in build v0.1.1
Updated the reference to it's full path 'File -> Preferences -> Settings -> Extensions -> Atari Dev Studio'
Added a const to the application area to define the path and replaced all references in code.
Reviewed the help and AtariAge post to update any references and added a blurb about the settings.

**Comment by SmallRoomLabs** [comment]
On Mac the preferences are located under the "Code" heading, not the "File"

<img width="549" alt="Screen Shot 2019-04-20 at 11 36 39 AM" src="https://user-images.githubusercontent.com/325326/56455609-b834f780-6360-11e9-9104-1a40a259a813.png">

**Comment by chunkypixel** [comment]
(re)Completed in build v0.1.1
Ah good point - updated!
