### ISSUE TITLE
Problem with launching Stella emulator and space in user directory

### ISSUE THREAD

**Issue by vbauer** [chunkypixel/atari-dev-studio#31]
Hello! I wanted to check atari-dev-studio on Windows 10 and faced with problem corresponding to paths.. My user folder contains space symbol - "Vladislav Bauer" (yes, it was my silly mistake...) When I try to compile and run project I see that compilation phase works fine, but Stella emulator could not be launched

OUTPUT from VS Code:
```
Starting build of FIFA1977.bas...
batari Basic v1.5 (c)2020
2600 Basic compilation complete.
      2254 bytes of ROM space left

Complete.

Verifying compiled file(s)...
Cleaning up files generated during compilation...
Moving compiled file(s) to 'bin' folder...
Moving debugger file(s) to 'bin' folder...

Launching Stella emulator...
'c:\Users\Vladislav' is not recognized as an internal or external command,
operable program or batch file.

Exit code: 1
```

Path to test project is "C:\Users\Vladislav Bauer\Documents\workspace\atari\Atari-Games\FIFA1977"

Perhaps it is connected to "spawn" usage, but until I figured out how to check or fix it
- https://github.com/chunkypixel/atari-dev-studio/blob/e6e105d01fe52ec6f94eeaca30ec2c9353dacea9/src/emulators/stellaEmulator.ts#L77
- https://github.com/chunkypixel/atari-dev-studio/blob/e6e105d01fe52ec6f94eeaca30ec2c9353dacea9/src/compilers/batariBasicCompiler.ts#L54

**Comment by chunkypixel** [comment]
Hi Vlad!
Thanks for raising this - really thought I'd got all these space issues sorted (had a big run through them recently). Any paths with spaces required "quoting" via the command-line.  

Will try and fix that tonight.

**Comment by chunkypixel** [comment]
Fixed refer build 0.5.3
Thanks again for reporting Vlad - related again to quoting the command path (hopefully that will be it!!)

**Comment by vbauer** [comment]
Thank you very much, Matthew!! Everything works great in v0.5.3

**Comment by chunkypixel** [comment]
Awesome thanks for letting me know!
