### ISSUE TITLE
Build and Launch on Mac

### ISSUE THREAD

**Issue by Generation2Games** [chunkypixel/atari-dev-studio#36]
When hitting Build & Launch on the Mac, it launches before a new build is created and launches older bin files on occassion.

**Comment by chunkypixel** [comment]
@Generation2Games Sorry mate just seen this.  Has this issue been happening for a while?  All platforms follow the same process so not sure what might be the problem on macOS (my virtual install is currently unavailable so I'll need to set it up again).  Does the compile log show anything as being skipped?

**Comment by Generation2Games** [comment]
My mistake.... it was leaving it open in the background then trying to launch another build, with the old build still open. Maybe it could close Stella before it launches a new build, or I could be less of an idiot? Either way lol
