### ISSUE TITLE
Compiling/emulating

### ISSUE THREAD

**Issue by darkstrings** [chunkypixel/atari-dev-studio#38]
When I go to ads in command palette and choose to compile and emulate, nothing happens. Well compiling may be happening but it doesn't show anything on screen or ask me where to put the compiled file. No stella for sure. Is there something I'm missing? I left everything default. 

Thanks so much!
-Lucien

**Comment by chunkypixel** [comment]
Hi Lucien,

2 things to confirm:

1. maybe check that the extension is loading correctly via the Help -> Toggle Developer Tools option (choose the Console tab in the tools to see the start log).
![ads-debug](https://user-images.githubusercontent.com/20292815/106066320-b95ba100-6150-11eb-9bbd-02a95a2889a1.png)

2. verify the language being used by your file (bottom right of the status bar will show the language chosen by VS Code). If it's not batari Basic (assumed) then click on the name shown to display the language selector:
![ads-language](https://user-images.githubusercontent.com/20292815/106066602-371fac80-6151-11eb-9656-e07830539063.png)

Also check Compiler dump via the Output window.

Hope that helps!

**Comment by darkstrings** [comment]
Hi chunkypixel!
Thanks for taking the time!

Here's what I see in console.
![error1](https://user-images.githubusercontent.com/78057999/106397228-436a6a80-63da-11eb-8f32-15b0ee28751f.png)

And here's what I see for language options
![image](https://user-images.githubusercontent.com/78057999/106397262-6eed5500-63da-11eb-9111-cb6c5067ed49.png)

**Comment by chunkypixel** [comment]
Hi @darkstrings,

Ok - first part confirmed that bB language and compiler is working! Can you re-open the debugger and choose the compile and run option? I output a lot of stuff to the console log which might help us understand why Stella is not launching 👍

**Comment by darkstrings** [comment]
Ahhh I found it....It was a typo + me not using visual in years so still seeing where everything is now. (Like output>debugger hahaha)

Thanks again so much!!!!

**Comment by chunkypixel** [comment]
@darkstrings Good stuff - glad its sorted an now working!  Yeah it's not as intuitive first up but great once you get up and running.
