### ISSUE TITLE
Syntax highlighter for dash fails for "ds"

### ISSUE THREAD

**Issue by SmallRoomLabs** [chunkypixel/atari-dev-studio#4]
The "ds" pseudo-op should probably be highlighted the same as the other like org/seg/include, now the "d" takes on the label color and the "s" is the constants color.
<img width="393" alt="Screen Shot 2019-04-20 at 9 40 07 AM" src="https://user-images.githubusercontent.com/325326/56454481-54570280-6351-11e9-86b0-2a9694534338.png">

**Comment by chunkypixel** [comment]
Thanks will try and sort that out 👍

**Comment by chunkypixel** [comment]
Completed in build v0.1.1
Looks like the label pattern was bleeding over into the next definition (don't fully understand patterm matching TBH).  Hopefully not affacted anything else!
