### ISSUE TITLE
6502 DEC Hover Incorrect

### ISSUE THREAD

**Issue by chunkypixel** [chunkypixel/atari-dev-studio#45]
As noted by Al_Nafuur the DEC hover is wrong.  Also review all again.
https://atariage.com/forums/topic/290365-atari-dev-studio-for-homebrew-development-release/?do=findComment&comment=4988310
![asm-dec](https://user-images.githubusercontent.com/20292815/150269565-2bc742f2-b0d3-4e64-8047-0585f8b219a5.jpg)

**Comment by DChristianson** [comment]
Hi @chunkypixel I thought we fixed this? But I'm seeing the old file in the last update 

https://github.com/chunkypixel/atari-dev-studio/commit/0d38a629c2baf26f81a79560353696c28d197c45

I'm seeing a new problem on VSCode mac - I think it stopped liking the 6502.md file altogether (I suspect to do with indents in the md):

<img width="644" alt="image" src="https://user-images.githubusercontent.com/2652188/154895364-59c808f5-18fb-4a77-aca2-e3a0a93c39cc.png">

**Comment by chunkypixel** [comment]
@DChristianson 
Hey! This seems to be a recent change in VS Code! Hadn't had a chance to take a look as yet.  Will try and have a play this week as I have a few spare nights.

**Comment by chunkypixel** [comment]
Seems like this was a bug in VSCode as the latest versions appears to have fixed the problem.
