### ISSUE TITLE
Usage of status line

### ISSUE THREAD

**Issue by SmallRoomLabs** [chunkypixel/atari-dev-studio#5]
I just realized that this extension is using quite a lot of real estate of the status line - and it's there all the time, not just when I'm in a ADS folder/workspace.

I couldn't find any guidelines for the usage of the status line, but personally I don't think it's totally ok to hog a lot of space there - especially for a specialized extension like this.

But I really like how easy it is to access the compile/run button...

A solution to this could be to have the usage of the status line disabled by default, and then let the user enable it in the workspace or folder preferences.  Then the buttons could be easily accessible from the projects where I do Atari coding, but be completely out of the way when I do other stuff.

**Comment by chunkypixel** [comment]
Completed is v0.1.2
Added new option to settings 'Whether to show the short-cut commands on the Status Bar (restart required)'.

Good idea! I'm expecting most users to not be familiar with VS Code so wanted a simple way to compile but yep advanced users may want to remove.  I'll need to work on the keyboard shorts soon.
