### ISSUE TITLE
Compiler missing since update

### ISSUE THREAD

**Issue by Generation2Games** [chunkypixel/atari-dev-studio#52]
Since updating to new version I get this error on build, please can you advise?

Verifying compiler files exist...
Verifying file permissions...
/bin/sh: /Users/xxxxxxxxx/.vscode/extensions/chunkypixel.atari-dev-studio-0.10.0/out/bin/compilers/bB/2600basic.sh: /bin/sh^M: bad interpreter: No such file or directory
Exit code: 126
Cleaning up files generated during compilation...

**Comment by chunkypixel** [comment]
Hi,
Really sorry for this issue.  I'm going to do some further testing on Linux to see what might be the cause of the problem (macOS and Linux are configured almost the same for this.)
Matt

**Comment by mengstr** [comment]
The shell file has CRLF endings which probably is the cause of the problem - I can't run it either on macOS.

```
mats@Matss-MacBook-Pro bB % hexdump -C 2600basic.sh | head -10
00000000  23 21 2f 62 69 6e 2f 73  68 0d 0a 0d 0a 23 20 64  |#!/bin/sh....# d|
00000010  6f 20 73 6f 6d 65 20 71  75 69 63 6b 20 73 61 6e  |o some quick san|
00000020  69 74 79 20 63 68 65 63  6b 69 6e 67 2e 2e 2e 0d  |ity checking....|
00000030  0a 0d 0a 69 66 20 5b 20  21 20 22 24 62 42 22 20  |...if [ ! "$bB" |
00000040  5d 20 3b 20 74 68 65 6e  0d 0a 20 20 65 63 68 6f  |] ; then..  echo|
```

**Comment by chunkypixel** [comment]
Thanks Mats - will take a look at that!

**Comment by chunkypixel** [comment]
Build 0.10.1 is up and should fix this problem.  Thanks again @mengstr !
