### ISSUE TITLE
Status line (again)

### ISSUE THREAD

**Issue by SmallRoomLabs** [chunkypixel/atari-dev-studio#6]
When I size VC to fit about half my screen width so I can have Stella in the other half (yea, I know that I really should have a dual screen setup but I like to code in the sofa) then the "rocket" in the status lines disappears.  Changing the name & version blurb to
`              { text: `ADS ${application.Version}` },`
makes it short enough to be displayed.

**Comment by chunkypixel** [comment]
I might look at some options like full (name and buttons), minimum (only buttons) and none - or if there is some way to prioritise what is shown when you minimise.

**Comment by chunkypixel** [comment]
Completed in v0.1.7
Replaced existing option with a drop-down selector to choose what you want to display (Full. Minimum, None)
