### ISSUE TITLE
Failed compilation artifacts

### ISSUE THREAD

**Issue by SmallRoomLabs** [chunkypixel/atari-dev-studio#8]
Every now and then I by mistake don't have the actual assembly file open by rather one of the .h files or something else when I press the compile/launch button. I then end up with a failed compilation and a couple of files ( .sym/.bin/.lst) generated by dasm that doesn't get cleaned up from my the main folder.

It's really not a biggie, but just kinda annoying.  

I'm not sure what the best fix would be for this. Always moving all build-artifacts to the bin folder is one solution, or maybe refusing to even try to compile a file that's not .a/.a65/.asm would be better...

**Comment by chunkypixel** [comment]
batariBasic and 7800basic compiles do clean up after themselves - but I haven't really done any work for dasm (my framework can do it though). I can also look at ensuring only the specific extensions process as you suggest.

**Comment by chunkypixel** [comment]
Completed in v0.1.7
Added process to remove files (.sym/.bin/.lst) where compilation or .bin validation fails
