### ISSUE TITLE
Race condition in "autosave before run" 

### ISSUE THREAD

**Issue by SmallRoomLabs** [chunkypixel/atari-dev-studio#9]
If I hit the compile or run buttons without saving the source first it seems like in about 20-25% of the cases the compile fails (usually giving a lot of "label mismatch" errors). Pressing the compile again always gives a clean compile.

I guess the saving is done asynchronously and dasm starts reading and processing the source before the save is fully finished.

**Comment by chunkypixel** [comment]
Thanks will check that out - thought I'd got all the async issues.

**Comment by chunkypixel** [comment]
Completed in v0.1.7
The build-in VS Code save routines are async'd which I didn't realise.
